### ISSUE TITLE
Propuestas

### ISSUE THREAD

**Issue by JSnow11** [JSnow11/web#13]
# descripcion
proponer una tarea propia o en conjunto a realizar que ocupe unas 3 horas de trabajo

**Comment by Javitoox** [comment]
- Personalizar las tarjetas de visita del apartado de ponentes

**Comment by danidinogo** [comment]
- Meter una flag dentro de la web para capturarla como minijuego con motivo de la temática de este año. Puede ser sencillito, como escribir comentarios dentro del código de la página, que te den una pista y hagas un siguiente escenario, y que los usuarios que la consigan puedan salir dentro de la web

**Comment by JSnow11** [comment]
- Tematizar la web, restilar y añadir elementos, iconos, imagenes ... relacionados con la ciberseguridad

**Comment by JSnow11** [comment]
- Pedir a prensa blogposts para añadir

**Comment by JSnow11** [comment]
- Reestructurar la página de inicio para que tenga una introducción más llamativa (podría enlazar con el minijuego ctf

**Comment by pedalopon** [comment]
Reestructurar/Redecorar la pagina de noticias y a lo mejor introducir un plugin que las personas que pongan su correo les lleguen las noticias nuevas que vayamos publicando

**Comment by Javitoox** [comment]
- Añadir las nuevas redes sociales creadas este año como Twitch

**Comment by Javitoox** [comment]
- Mejorar el posicionamiento de la página en la red para alcanzar un mayor número de interesados

**Comment by pabmatale** [comment]
Incluir Elementor como plugin para personalizar y rediseñar la web para darle un aspecto mas atractivo y dinamico.
