### ISSUE TITLE
Task: Actualizar programa temporal

### ISSUE THREAD

**Issue by JSnow11** [JSnow11/web#16]
# description
En la sección Programa se debe de actualizar la información de las actividades que se van a desarrollar

Los asignados deberán seleccionar uno de los días y actualizar el horario, deben comunicar en este propio issue cual han seleccionado para que los demás lo sepan.

## programa
[20211022_Horario_Innosoft_21.pdf](https://github.com/JSnow11/web/files/7412327/20211022_Horario_Innosoft_21.pdf)

 # to-do
- [x] #17
- [x] #18
- [x] #19
- [x] #20

# accept
- [x] El programa está actualizado

**Comment by danidinogo** [comment]
Chavales, no sé leer y lo he hecho todo, perdonadme, me he visto en la tarea y he procedido @JSnow11 @Javitoox @AlvarofbUS @pedalopon . Habladme por telegram, mi tarea de ponentes aún no la he hecho, por intercambiaros el tiempo o algo

**Comment by JSnow11** [comment]
# review
- sería interesante añadir los ponentes y linkearlos a la página de ponentes

@kwertyx
