### ISSUE TITLE
Task: CTF

### ISSUE THREAD

**Issue by JSnow11** [JSnow11/web#44]
# description
se pretende tener un minijuego ctf acorde a la temática de las charlas

se sugiere alguna tarea sencilla de inspección de la página o algo por el estilo que lleve a una vista de felicitación y resultado (posible ranking)

este minijuego saltará cuando se pulse en un boton en la pagina principal

 # to-do
- [x] seleccionar el minijuego (posible ayuda en el canal de telegram de ciberseguridad o en hack the box)
- [x] implementación
- [x] trigger en la pagina principal

# accept
- [x] ctf accesible desde la pagina de inicio
- [x] pagina de resultado

**Comment by danidinogo** [comment]
Añadido resultados en forma de widget en la página de inicio. Si se quiere añadir la tabla a cualquier página, se puede usar el shortcode: [innosoft_ctf]
