### ISSUE TITLE
Task: Mejora visual noticias

### ISSUE THREAD

**Issue by JSnow11** [JSnow11/web#48]
# description
mejorar generalmente la lista de noticias y blogposts

 # to-do
- [x] analisis de plugin utilizado
- [x] rediseño / reelección de plugin

# accept
- [ ] la página de noticias tiene un nuevo diseño acorde al cartel y la temática

**Comment by manoutbar** [comment]
Tras analizar la existencia de plugins existentes frente a la gestión actual de noticias no se contempla la opción de incluir nuevos plugins dado que con poco tiempo se ha llegado a rediseñar correctamente la sección de noticias.

El coste sin embargo de incluir un plugin pasaba por migrar todo el contenido actual además de retocar visualmente hasta ajustar la visualización al tema actual de la web
