### ISSUE TITLE
Task: entradas segundo lunes

### ISSUE THREAD

**Issue by JSnow11** [JSnow11/web#61]
# description
Asegurarse que los enlaces y horas concuerdan con este horario

Introducción al Hacking 1 8:30 – 9:30: 

https://www.eventbrite.es/e/entradas-introduccion-al-hacking-205219465947

Introducción al Hacking 2 9:30 - 10:30: 

https://www.eventbrite.es/e/entradas-introduccion-al-hacking-209734209667

Introducción al Hacking 3 10:30 – 11:30:

https://www.eventbrite.es/e/entradas-introduccion-al-hacking-209735463417

Introducción al Hacking 4 11:30 – 12:30: 
https://www.eventbrite.es/e/entradas-introduccion-al-hacking-209735814467

Comienzo en la ciberseguridad 10:30 – 11:30:

https://www.eventbrite.es/e/entradas-comienzo-en-la-ciberseguridad-por-donde-empiezo-
205230067657

Ciberseguridad, ¿Qué esperan estudiar y donde esperan estudiarlo? 11:30 –
12:30: 

https://www.eventbrite.es/e/entradas-ciberseguridad-que-esperan-los-alumnos-estudiar-y-
donde-lo-esperan-205233046567

De que hablamos cuando hablamos de ciberseguridad 17:30 – 18:30: 

https://www.eventbrite.es/e/entradas-de-que-hablamos-cuando-hablamos-de-
ciberseguridad-209737008037

Recorrido de las Programadoras 17:30 – 18:30: 

https://www.eventbrite.es/e/entradas-recorrido-de-las-programadoras-209737820467

Seguridad de los servicios en la nube 18:30 – 19:30: 

https://www.eventbrite.es/e/entradas-seguridad-en-los-servicios-en-la-nube-209738943827

Ciberseguridad y Hacking ético 18:30 – 19:30: 

https://www.eventbrite.es/e/entradas-ciberseguridad-y-hacking-etico-209741421237

 # to-do
- [x] añadir enlaces

# accept
- [x] entradas obtenibles desde la web

**Comment by pedalopon** [comment]
Las horas están mal, las de la web y las de la página de Eventbrite están bien.
