### ISSUE TITLE
Task: cambiar fechas del calendario (programa)

### ISSUE THREAD

**Issue by JSnow11** [JSnow11/web#7]
# description
Cambiar las fechas del
calendario a las fechas
actualizadas de este año, aunque
no existan actividades
programadas para esas fechas
(están en las diapositivas de
presentación) 

 # to-do
- [x] crear pagina para la nueva edición
- [x] crear el nuevo calendario (plugin)
- [x] añadir fechas posibles
- [x] añadir al menú

# accept
- [x] nuevo calendario visible https://institucional.us.es/innosoft/programa-viii-edicion/

**Comment by danidinogo** [comment]
Publicado en esta página:
https://institucional.us.es/innosoft/programa-ix-edicion/
