### ISSUE TITLE
Task: añadir ponente Sergio Medina + Avenade

### ISSUE THREAD

**Issue by JSnow11** [JSnow11/web#70]
# description
la ponencia debe actualizar su ponente, sustituyendo Microsoft por Sergio Medina

Sergio Medina + Avenade debe ser un ponente.

descripción: Sergio trabaja en el sector de la ciberseguridad desde hace más de 15 años. Actualmente desempeña el rol de Cloud Solutions Architect en Microsoft. En este puesto ayuda a los socios tecnológicos de Microsoft a desarrollar todo su potencial. Su misión principal es que exploten al máximo las tecnologías que ofrece la compañía de Redmond en materia de seguridad, identidad y cumplimiento normativo.

foto:
![IMG_20211117_105143.jpg](https://user-images.githubusercontent.com/47798577/142177773-14190ac8-5955-40db-b9e6-d792fa76255b.jpg)

 # to-do
- [x] sustituir ponente en la ponencia del programa
- [x] añadir ponente

# accept
- [x] Sergio + Avenade aparece como ponente

**Comment by pedalopon** [comment]
No se puede subir la imagen del ponente a wordpress, @JSnow11

**Comment by JSnow11** [comment]
> No se puede subir la imagen del ponente a wordpress, @JSnow11 

# review
La imagen no puede añadirse por problemas técnicos con wordpress.

@kwertyx podría estar relacionado con el problema que detectaste con los permisos de edición?
